site_name: zkWasm Development Recipe
nav:
  - Home: index.md
  - Getting Started:
    - Setup Environment: Setup Environment.md
    - Quick Tutorial: Quick Tutorial.md
  - Core Documentation:
    - Core Concepts: Core Concepts.md
    - zkWasm Overview: zkWasm Overview.md
  - Development Guide:
    - zkWasm Rust SDK: zkWasm Rust SDK.md
    - zkWasm Mini Rollup: zkWasm Mini Rollup.md
  - Design Guide:
    - Design Application as State Machine: Design Application as State Machine.md
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js