site_name: zkWasm Development Recipe
site_url: https://development-recipe.zkwasm.ai
nav:
  - Home: index.md
  - Getting Started:
    - Setup Environment: getting-started/Setup Environment.md
    - Quick Tutorial: getting-started/Quick Tutorial.md
    - Development Workflow: getting-started/Development Workflow.md
  - Core Documentation:
    - Core Concepts: Core Concepts.md
    - zkWasm Overview: zkWasm Overview.md
  - Design Guide:
    - Design Application as State Machine: Design Application as State Machine.md
  - Development Guide:
    - zkWasm Rust SDK and Rest Service ABI: development-guide/zkWasm Rust SDK.md
    - Web3 Development Frameworks: development-guide/Web3 Development Frameworks.md
    - Implementing Time-Driven Events: development-guide/Implementing Time-Driven Events.md
    - Generating Random Numbers: development-guide/Generating Random Numbers.md
  - zkWasm Mini Rollup:
    - Overview: zkwasm-mini-rollup/Rollup Overview.md
    - Host Environment: zkwasm-mini-rollup/Rollup Host.md
    - Database Service: zkwasm-mini-rollup/Rollup Database.md
    - Server Implementation (zkWasm-ts-Server): zkwasm-mini-rollup/Rollup Server.md
    - Convention: zkwasm-mini-rollup/Rollup Convention.md
  - zkWasm Protocol:
    - zkWasm Protocol Overview: zkwasm-protocol/zkWasm Protocol.md
    - Deposit: zkwasm-protocol/Deposit.md
    - Withdraw: zkwasm-protocol/Withdraw.md
    - Custom Transaction: zkwasm-protocol/Custom Transaction.md
  - Additional Resources:
    - Official Links: additional-resources/Official Links.md
    - Project Examples: additional-resources/Project Examples.md
    - Frequently Asked Questions: additional-resources/Frequently Asked Questions.md

theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: lime
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - content.code.copy
    - search.highlight
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.highlight
use_directory_urls: false
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - https://unpkg.com/mermaid@10.6.1/dist/mermaid.min.js